#!/usr/bin/env php
<?php

error_reporting(E_ALL & ~E_DEPRECATED);

use Illuminate\Contracts\Console\Kernel;

define('LARAVEL_START', microtime(true));

require_once __DIR__.'/vendor/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';

$kernel = $app->make(Kernel::class);

$status = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);

$kernel->terminate($input, $status);

exit($status);
